<?php

return [
    'name' => 'MyStore',
    'avatar' => 'images/no_avatar.jpg',
    'number' => 0,
    'paginate' => 1,
    'images_folder' => 'storage/images/',
    'role_supplier' => 2,
    'role_supplier_name' => 'Supplier',
    'role_admin' => 1,
    'role_admin_name' => 'Admin',
    'role_user' => 3,
    'role_user_name' =>  'User',
    'status_block' => -1,
    'status_block_name' => 'block',
    'status_block_class' => 'danger',
    'status_not_active' => 0,
    'status_not_active_name' => 'Not Actived',
    'status_not_active_class' => 'warning',
    'status_active' => 1,
    'status_active_name' => 'Activated',
    'status_active_class' => 'success',
    'order_status_cancel'=> -2,
    'order_status_refuse' => -1,
    'order_status_pending' => 0,
    'order_status_accept' => 1,
    'order_status_finish' =>2,
    'order_status_cancel_name' => 'resfused',
    'order_status_refuse_name' => 'canceled',
    'order_status_pending_name' => 'pending',
    'order_status_accept_name' => 'accepted',
    'order_status_finish_name' => 'finished',
    'order_status_cancel_class' => 'danger',
    'order_status_refuse_name' => 'default',
    'order_status_pending_name' => 'warning',
    'order_status_accept_name' => 'primary',
    'order_status_finish_name' => 'success',
    'vnd' => 'VND',
    'payment_method' => 2,
    'format' => 'd/m/Y',
];
