<?php

return [
    'company_name' => 'MyMarket',
    'logo' => 'storage/images/my-market-logo.png',
    'icon' => 'storage/images/my-market-icon.png',
    'england_flag' => 'storage/images/england-flag.png',
    'vietnamese_flag' => 'storage/images/vietnamese-flag.png',
    'published_year' => '2020',
    'version' => '1.0',
    'max_rating' => '5',
    'date_format' => 'd/m/Y',
    'image_folder' => '/storage/images/',
    'get_child_categories_url' => 'get-child-categories/',
    'l_size' => 'L',
    'default_image' => 'images/no_image.png',
    'weight_unit' => 'gram',
    'default_product_thumbnail' => 'no_image.png',
    'default_user_image' => 'default_user_image.jpg',
    'admin_id' => 1,
    'supplier_id' => 2,
    'customer_id' => 3,
    'pending_id' => 1,
    'active_id' => 2,
    'blocked_id' => 3,
    'throttle_resend_mail_times' => 3,
    'throttle_resend_mail_minutes' => 1,
];
