<?php

return [
    'company_name' => 'MyMarket',
    'logo' => 'storage/images/my-market-logo.png',
    'icon' => 'storage/images/my-market-icon.png',
    'england_flag' => 'storage/images/england-flag.png',
    'vietnamese_flag' => 'storage/images/vietnamese-flag.png',
    'published_year' => '2020',
    'version' => '1.0',
    'max_rating' => '5',
    'date_format' => 'd/m/Y',
    'image_folder' => '/storage/images/',
    'get_child_categories_url' => '/get-child-categories/',
    'l_size' => 'L',
    'default_image' => 'images/no_image.png',
    'weight_unit' => 'gram',
    'default_product_thumbnail' => 'images/no_image.png',
    'default_user_image' => 'images/default_user_image.jpg',
    'admin_id' => 1,
    'supplier_id' => 2,
    'customer_id' => 3,
    'pending_id' => 0,
    'active_id' => 1,
    'blocked_id' => 2,
    'throttle_resend_mail_times' => 3,
    'throttle_resend_mail_minutes' => 1,
    'currency_unit' => 'đ',
    'default_user_avatar' => 'default_user_image.jpg',
    'facebook_logo' => 'storage/images/facebook_logo.png',
    'youtube_logo' => 'storage/images/youtube_logo.png',
    'facebook_link' => 'https://www.facebook.com/mymarket',
    'youtube_link' => 'https://www.youtube.com/channel/mymarket',
    'default_cart_item_quantity' => 1,
    'deadline_time' => '23:59',
    'commissions_percent' => '0.02',
    'commissions_start_day' => '19',
    'commissions_end_day' => '19',
    'commissions_send_mail_day' => '18',
    'commissions_send_mail_time' => '10:39',
    'bank_name' => 'Vietcombank',
    'bank_account_owner' => 'NGUYEN QUANG LINH',
    'bank_account_number' => '123456789',
    'bank_branch' => 'Me Tri',
];
